#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl5,  ultraSonic,     sensorSONAR_inch)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title:Design a Machine
Team Members:Andres Arrizon, Anderson Lovett, Arnav Gahlot
Date:2/25/2019
Section:N/A


Task Description:


Pseudocode:

*/

task main()
{																																	// wait for bump to be pressed
	untilDark(350, lightSensor);
	turnFlashlightOn(flashlight, 127);

	untilBump(bumpSwitch);
	startMotor(rightMotor, 63);
	startMotor(leftMotor, -63);                                     //Program begins, insert code within curly braces

	untilSonarLessThan(10, ultraSonic);
	startMotor(rightMotor, 63);
	startMotor(leftMotor, 63);
	wait(0.78);
	startMotor(rightMotor, 63);
	startMotor(leftMotor, -63);
	wait(2);




}
