#pragma config(Sensor, dgtl1,  bump1,          sensorTouch)
#pragma config(Sensor, dgtl6,  bump2,          sensorTouch)
#pragma config(Sensor, dgtl9,  encoder,        sensorQuadEncoder)
#pragma config(Motor,  port2,           driver,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           hammer,        tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: Auto - Piano Player
Team Members: Arnav Gahlot, Andres Arrizon, Anderson Lovett
Date:03/19/2019
Section:


Task Description: plays given song, on the push of a button


Pseudocode:

*/

task main()
{
	int encoderIN = 0;
	SensorValue(encoderIN)=0;

	untilBump(bump2, 1);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 15);
	wait(0.1);

	startMotor(driver, -40);
	untilEncoderCounts(-375, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, -40);
	untilEncoderCounts(-6, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, -45);
	untilEncoderCounts(-7, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, 40);
	untilEncoderCounts(10, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, 40);
	untilEncoderCounts(10, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, -40);
	untilEncoderCounts(-6, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, 40);
	untilEncoderCounts(5.5, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, 40);
	untilEncoderCounts(40, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);


	startMotor(driver, -40);
	untilEncoderCounts(-40, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, -40);
	untilEncoderCounts(-6, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, -45);
	untilEncoderCounts(-7, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, 40);
	untilEncoderCounts(10, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, 40);
	untilEncoderCounts(10, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, -40);
	untilEncoderCounts(-6, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, 40);
	untilEncoderCounts(7, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, -40);
	untilEncoderCounts(-7, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

	startMotor(driver, -40);
	untilEncoderCounts(-10, encoder);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);

}//
