#pragma config(Sensor, dgtl1,  bump1,          sensorTouch)
#pragma config(Sensor, dgtl6,  bump2,          sensorTouch)
#pragma config(Motor,  port2,           driver,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           hammer,        tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: Auto - Piano Player
Team Members: Arnav Gahlot, Andres Arrizon, Anderson Lovett
Date:03/19/2019
Section:


Task Description: plays given song, on the push of buttons


Pseudocode:

*/

task main()
{
	untilBump(bump2, 1);
	startMotor(hammer, -22);
	wait(0.2);
	startMotor(hammer, 19);
	wait(0.2);
	startMotor(driver, -30);
	wait(1.127);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.6);
	startMotor(hammer, 19);
	wait(0.5);
	startMotor(driver, -30);
	wait(0.11);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.6);
	startMotor(hammer, 19);
	wait(0.5);
	startMotor(driver, -30);
	wait(0.11);
	stopMotor(driver);
	startMotor(hammer, -22);
	wait(0.6);
	startMotor(hammer, 19);
	wait(0.6);
}//
